<?php
$this->headLink()
    ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.datatables/bootstrap-adapter/css/datatables.css')
    ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.niftymodals/css/component.css');
?>


<div class="modal fade" id="mod-warning" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="i-circle warning"><i class="fa fa-warning"></i></div>
                    <h4>Warning!</h4>
                    <p>Something is going wrong here...</p>
                    <textarea class="form-control"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-warning btn-flat" data-dismiss="modal">Proceed</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade in" id="mod-info" tabindex="-1" role="dialog">
    <div class="modal-dialog" id="manam">
    </div><!-- /.modal-dialog -->
</div>

<div class="table-responsive">
    <table  class="table table-bordered" id="datatable" >
        <thead>
            <tr>
                <th>Company Name</th>
                <th>Economic Code</th>
                <th>Status</th>
                <th>Activation</th>
                <th>Management</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($users as $user) : ?>
            <tr class=" ">
                <td><?php echo $user->getUsername() ?></td>
                <td><?php echo $user->getEmail() ?></td>
                <td><?php echo ucfirst($user->getStatus()) ?></td>
                <td class="center">
                    <div class="btn-group">
                        <button class="btn btn-default btn-xs" type="button">Actions</button>
                        <button data-toggle="dropdown" class="btn btn-xs btn-primary dropdown-toggle" type="button">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul role="menu" class="dropdown-menu">
                            <li class="get-user">
                                <a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'activation' ,'action' => 'enable', 'id' => $user->getId()]); ?>">Enable</a>
                            </li>
                            <li><a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'activation' ,'action' => 'disable', 'id' => $user->getId()]); ?>">Disable</a></li>
                            <li class="divider"></li>
                            <li data-toggle="modal" data-target="#mod-warning">
                                <a href="#">Block</a>
                            </li>
                        </ul>
                    </div>
                </td>
                <td class="center">
                    <div class="btn-group">
                        <button class="btn btn-default btn-xs" type="button">Actions</button>
                        <button data-toggle="dropdown" class="btn btn-xs btn-primary dropdown-toggle" type="button">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'manage' ,'action' => 'edit', 'id' => $user->getId()]); ?>">Edit</a></li>
                            <li><a href="#">Details</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'manage' ,'action' => 'delete']); ?>">Remove</a></li>
                            <li><a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'manage' ,'action' => 'delete']); ?>">Assign Service</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
