<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
        <div class="text-center">
            <div class="i-circle info"><i class="fa fa-check"></i></div>
            <h4>Awesome!</h4>
            <p>Changes has been saved successfully!</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
        <button type="button" id="not-primary" class="btn btn-info btn-flat" data-dismiss="modal">Proceed</button>
    </div>
</div><!-- /.modal-content -->
