<div class="block-flat">
    <div class="header">
        <h3>Offer List</h3>
    </div>
    <div class="content">
        <div class="list-group">
            <?php foreach($this->requests as $req):?>
                <a href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'b2b' ,'action' => 'requestdetail', 'id' => $req->getId()]); ?>" class="list-group-item">
                    <h5 class="list-group-item-heading">Company: <?php echo $req->getUser()->getusername() ?></h5>
                    <div><i class="fa fa-mobile-phone"></i> <?php echo $req->getUser()->getDetails()->getPhone() ?></div>
                    <div><i class="fa fa-envelope"></i> <?php echo $req->getUser()->getEmail() ?></div>
                    <div><i class="fa fa-envelope"></i> <?php echo $req->getService()->getServiceLang()[1]->getName() ?></div>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>
